const SUBSCRIPTION_FEE_INR = 1000;
const YEARLY_PLAN_DISCOUNT_PERCENT = 10;
const YEARLY_SUBSCRIPTION_FEE_INR = SUBSCRIPTION_FEE_INR * 12 * ((100 - YEARLY_PLAN_DISCOUNT_PERCENT) / 100);
const CONTRIBUTION_DEFAULT_PERCENT = 10;
const CONTRIBUTION_MIN_PERCENT = 10;
const CONTRIBUTION_MAX_PERCENT = 100;
const SUBSCRIPTION_DURATION_DAYS = 30;
const YEARLY_SUBSCRIPTION_DURATION_DAYS = 365;
const SCORE_MIN = 1;
const SCORE_MAX = 45;
const SCORE_LIMIT = 5;
const DRAW_POOL_SIZE = 45;
const DRAW_NUMBERS_COUNT = 5;
const DRAW_WIN_THRESHOLD = 3;
const DRAW_COOLDOWN_HOURS = 0;
const PRIZE_POOL_PERCENTAGE = 50;
const PRIZE_DISTRIBUTION = {
  5: 0.4,
  4: 0.35,
  3: 0.25
};

const JWT_ACCESS_EXPIRY = '15m';
const JWT_REFRESH_EXPIRY = '7d';
const REFRESH_COOKIE_NAME = 'refresh_token';

module.exports = {
  SUBSCRIPTION_FEE_INR,
  YEARLY_PLAN_DISCOUNT_PERCENT,
  YEARLY_SUBSCRIPTION_FEE_INR,
  CONTRIBUTION_DEFAULT_PERCENT,
  CONTRIBUTION_MIN_PERCENT,
  CONTRIBUTION_MAX_PERCENT,
  SUBSCRIPTION_DURATION_DAYS,
  YEARLY_SUBSCRIPTION_DURATION_DAYS,
  SCORE_MIN,
  SCORE_MAX,
  SCORE_LIMIT,
  DRAW_POOL_SIZE,
  DRAW_NUMBERS_COUNT,
  DRAW_WIN_THRESHOLD,
  DRAW_COOLDOWN_HOURS,
  PRIZE_POOL_PERCENTAGE,
  PRIZE_DISTRIBUTION,
  JWT_ACCESS_EXPIRY,
  JWT_REFRESH_EXPIRY,
  REFRESH_COOKIE_NAME
};
